### ISSUE TITLE
Connection aborted, error(10054)

### ISSUE THREAD

**Issue by ALEERQUESON2DIAS** [mk-fg/python-onedrive#47]
Hello, 

I am running version 15. 01. 10 installed again in a clean way.

While I do not consider this issue as a program error, I put it here if you could provide any solution from the PYTHON-ONEDRIVE program and in case it were interesting to other users who may experience this problem due to growing their data volume.

Onedrive stage is as follows: Three folders in OneDrive

A folder named DAT with more than 30. 000 files
A folder named INF with 487 files in 10 subfolders
A folder named CONTROL with 31 files in 8 subfolders

Any access to get files from INF or CONTROL folders works correctly (Only get operations)

On the other hand, any attempt to access and download files from DAT folder just end abnormally with message 

onedrive.api_v5.ProtocolError: (None, "('Connection aborted.', error(10054, 'Se ha forzado la interrupci\\xf3n de una conexi\\xf3n existente por el host remoto'))")

I created for testing a new folder named PRU and copied in it two files from DAT. Access to these files under PRU is correct.

I can deduce that the problem may be due to an excessive amount of files in folder DAT. 
 
Despite my adsolutely no knowledge of programming in Python language, it can be seen in the source that  tries a LISTDIR function that may not be completed.

Is there any solution possible from python-onedrive or on the contrary it is neccesary to modify the DAT folder structure?

Thank you and best regards

Below is the complete sequence of trace 

C:\Users\ANGEL>onedrive-cli -c "B:/OD.lcrc" get "ALQS2D/DAT/filetest.txt"  "%USERPROFILE%/AppData/Temp/filetest.txt"
Traceback (most recent call last):
  File "C:\Python27\Scripts\onedrive-cli-script.py", line 9, in <module>
    load_entry_point('python-onedrive==15.01.10', 'console_scripts', 'onedrive-cli')()
  File "C:\Python27\lib\site-packages\onedrive\cli_tool.py", line 332, in main
    contents = api.get(resolve_path(optz.file), byte_range=optz.byte_range)
  File "C:\Python27\lib\site-packages\onedrive\cli_tool.py", line 255, in <lambda>
    resolve_path = ( (lambda s: id_match(s) or api.resolve_path(s))\
  File "C:\Python27\lib\site-packages\onedrive\api_v5.py", line 592, in resolve_path
    root_id = dict(it.imap(op.itemgetter('name', 'id'), self.listdir(root_id)))[name]
  File "C:\Python27\lib\site-packages\onedrive\api_v5.py", line 608, in listdir
    .listdir(folder_id=folder_id, limit=limit, offset=offset)['data']
  File "C:\Python27\lib\site-packages\onedrive\api_v5.py", line 358, in listdir
    return self(ujoin(folder_id, 'files'), dict(limit=limit, offset=offset))
  File "C:\Python27\lib\site-packages\onedrive\api_v5.py", line 333, in __call__
    try: return self.request(api_url(), **kwz)
  File "C:\Python27\lib\site-packages\onedrive\api_v5.py", line 164, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (None, "('Connection aborted.', error(10054, 'Se ha forzado la interrupci\\xf3n de una conexi\\xf3n existente por el host remoto'))")

**Comment by mk-fg** [comment]
If you're doing "ls" on that dir (with a cli tool), have you checked the --help on that command?

    % ./onedrive-cli ls -h
    usage: onedrive-cli ls [-h] [-r {[offset]-[limit] | limit}] [-o] [folder]

    positional arguments:
      folder                Folder to list contents of (default: me/skydrive).

    optional arguments:
      -h, --help            show this help message and exit
      -r {[offset]-[limit] | limit}, --range {[offset]-[limit] | limit}
                            List only specified range of objects inside. Can be
                            either dash-separated "offset-limit" tuple (any of
                            these can be omitted) or a single "limit" number.
      -o, --objects         Dump full objects, not just name and id.

I suspect that you might want to pass some limits via "-r" option, so that onedrive connection won't time-out while it's generating multi-megabyte json of folder contents.

Don't think I'm aware of any other issues with huge number of files in dirs, except for that listing thing.

One usual solution to avoid worrying about such limits is to use some hash function to put files into "bucket dirs", but it's usually only applicable to files/dirs created and used in some automatic fashion (e.g. caches, databases, backups, fs backends, etc), i.e. not really human-usable.

**Comment by mk-fg** [comment]
Just noticed that you're actually doing the "get" of the file by its path, not "ls", so my suggestion above is probably not applicable, sorry.

OneDrive didn't really support "get dir/a/b/somefile.txt" last time I checked, only supporting getting the file by its "id" string (regardless of where it's actually located), so in order to do human-friendly "get dir/a/b/somefile.txt" operation, command-line tool does "resolve_path" first, which involves getting a list of OneDrive root files/dirs by it's well-known id ("me/skydrive"), finding id for "dir" there, getting list for that id, etc.

That "resolve_path" thing doesn't account for dirs like the one you have there, always trying to grab the full list.
Guess some checks and workaround for this particular case can be implemented there, but it'd still be quite slow and inefficient (making tons of extra requests), so if you have that DAT dir filled by some script or tool, maybe keeping a local index of file id's and requesting files by that (if necessary) would be still a better idea.

Workaround for current version might be requesting dir listing in chunks (as proposed above) with the "-o" option, finding necessary file there and requesting it by id - "get" should support it.
Guess best way to do that with this module would be from a python script, also caching "name-id" pairs locally, or failing that - process the cli tool output in some automated fashion (which is probably a bad idea, as it's not really designed for this).

**Comment by mk-fg** [comment]
Added per-500-items pagination to "resolve_path" method mentioned above in 64d35ba and 15.02.01, maybe try it and see if it will work for you?

500-item requests take a few (4-8) seconds, which shouldn't be enough to trigger any kind of timeout, even with OneDrive being under stress, I think.
Largest listing I've tried was 5k items, and it completed in ~70s, which seem to be pushing API limits a bit too far.

As for efficiency, as you can probably guess/calculate, to retreive file by its name among ~30k items, about 30 http requests will be required on average, 2-4 in the best case, ~60 - worst.
Requests for more items stop when the right name is found, hence the best/worst disparity.
Again, if you plan to routinely deal with such large directories, it might be a good idea to keep a local cache of file name-id pairs, to avoid this lenghty process entirely and be able to request correct file right away (in a single get request).

**Comment by ALEERQUESON2DIAS** [comment]
Hello

Thank you very much for the suggestion. I will do the test con nuew versión as soon as possible.

I did a test yesterday with 15.01.10 version in a 500 elements folder and works O.K. 

We are considering two options: ONE is perform a division of a such a huge directory in smaller folders ( the more suitable for us will be folders with about 1,5 to 2k elementes), and TWO work with file identifications. We have obtained the identification of a file but appears in two formats, such as <<id: 6ea482f9ed79f808>> and the two lines after <<id: file.6ea482f9ed79f808.6EA482F9ED79F808!74594>>

A problem we encounter is that we don't have clear which is onedrive-cli parameter format in the GET statement to facilitate a ID rather than a FILE NAME to get the file. We tried with help and we dikd some test by with NO success.

C:\Users\ANGEL>onedrive-cli get -h
usage: onedrive-cli-script.py get [-h] [-b BYTE_RANGE] file [file_dst]

positional arguments:
  file                  File (object) to read.
  file_dst              Name/path to save file (object) as.

optional arguments:
  -h, --help            show this help message and exit
  -b BYTE_RANGE, --byte-range BYTE_RANGE
                        Specific range of bytes to read from a file (default:
                        read all). Should be specified in rfc2616 Range HTTP
                        header format. Examples: 0-499 (start - 499), -500
                        (end-500 to end).

I will inform ypou about the test with new version as soon as possible. Could yo tell me te format of GET with identificactions?

Thanks you a lot for your time and your suggestions. Regards

**Comment by mk-fg** [comment]
Github seem to have snipped things with `<<...>>` around them from your last message, but I've got them from the notification mail:

> We have obtained the identification of a file but appears in two formats, such as `<<id: 6ea482f9ed79f808>>` and the two lines after `<<id: file.6ea482f9ed79f808.6EA482F9ED79F808!74594>>`

"File id" that I've been talking about is the latter one - `file.6ea482f9ed79f808.6EA482F9ED79F808!74594`, as presented by e.g. "info" command, or "ls -o".

The other id (`6ea482f9ed79f808`) is a user id, and you probably saw that one under "from:", e.g.:

    ...
    created_time: 2014-11-16T12:49:01+0000
    description: 
    from:
      id: 6ea482f9ed79f808
      name: ...
    id: file.6ea482f9ed79f808.6EA482F9ED79F808!74594
    is_embeddable: True
    link: ...
    name: 中文.txt
    parent_id: folder.6ea482f9ed79f808.6EA482F9ED79F808!123
    shared_with:
      access: Just me
    size: 53
    ...

It's a actually a tree structure, similar to [YAML format](https://en.wikipedia.org/wiki/YAML) or python syntax, so all the indented stuff under "from:" is an info about the user who uploaded the file - user id and name.

You can also see this user id included in the id for every file that you've ever uploaded from that account, it certainly isn't enough to identify any particular file.


Getting the file by id like `file.6ea482f9ed79f808.6EA482F9ED79F808!74594` with commandline tool's "get" should work - just use e.g. `onedrive-cli get 'file.6ea482f9ed79f808.6EA482F9ED79F808!74594'` (no idea if quotes are needed on windows, or if they maybe should be double-quotes), and seem to work fine here.
If it throws some error for you, looking at the traceback might help, maybe cmd.exe is mangling passed id somehow (might happen if "!" is something special there, and/or no quoting was used).

**Comment by ALEERQUESON2DIAS** [comment]
Hello and thank you very much again. I have installed and tested the new version 15. 02. 1

Tests conducted with the new version and their results are as follows:

1) download file using its identification is fast and it is independent of the folder structure and number of files inside it, such as you said. I didn´know before te existence of fileid's.
(2) Using the detailed full path for a file who is inside a folder with 0.5K files has a SUCCESFUL DOWNLOAD in about 15 seconds.
(3) Using the detailed full path for a file who is inside a folder with 2K files has a SUCCESFUL DOWNLOAD in about 25  seconds.

This download times are acceptable for us, but we will considered using of fileid's.

We have seen that obtaining fileid's  is possible with from ONEDIVE-CLI a folder level with 

                Onedrive-cli ls –o [foldername]

Is it possible to obtain fileids individually using onedrive-cli? 

We have tested    ls -o    using a filename instead a foldername and, logically, it said «not found»

The next step for us is to generate an executable bundled with onedrive-cli and all its accessories modules so that it can be excutable in a Windows environment that does not have Python, PyYAM, Py32win and so on, so that it can be called from user routines. Do you know if Is it possible?

Thank you very much for the information, the new release and your time and effort. Sincerely grateful.

**Comment by mk-fg** [comment]
> 1) download file using its identification is fast and it is independent of the folder structure and number of files inside it, such as you said. I didn´know before te existence of fileid's.

There are also --path (-p) and --id (-i) top-level options, which can be used with any command which takes file/folder argument to force treating it as a path or id (depending on option).

You might want to use -i, if you're always using ids for some ops, so that argument won't ever be mistaken for a filename.

> Is it possible to obtain fileids individually using onedrive-cli?

It is now.

Just added (0a14444 or 15.02.2) a global --object-key option, which can be used with any command that outputs objects (e.g. "ls -o"), for example `onedrive-cli -k id ls -o` should print a bunch of id's only, or `onedrive-cli -k id info somefile.txt` would only print id of a specified file.

More complex usage of this option can involve passing it a python format string, e.g. `{0[name]!r} {0[count]:04d}` (name repr + 0-prefixed 4-digit display of count), but you probably don't need that.
See `onedrive-cli -h` output for more details.

As also mentioned above, onedrive-cli is intended to be used by humans, and it might be way easier, efficient and more reliable to script whatever automated behavior you want in python, rather than parsing cli tool's output.

> We have tested ls -o using a filename instead a foldername and, logically, it said «not found»

Yeah, naturally, "ls" only works with folder names or id's, if you want to see metadata of one specified file/folder, use "info" command, e.g. `onedrive-cli info somedir/somefile.txt`.

> The next step for us is to generate an executable bundled with onedrive-cli and all its accessories modules so that it can be excutable in a Windows environment that does not have ... Do you know if Is it possible?

Yeah, definitely possible, and there should be a few tools to do that.

[py2exe](http://www.py2exe.org/) is the most well-known one, I think, followed by [PyInstaller](http://www.pyinstaller.org/) and [cx_Freeze](http://cx-freeze.sourceforge.net/), and there are probably others.
I've never used python on windows directly, and have no experience with any of the above tools, so can't really make any recommendations here.

**Comment by ALEERQUESON2DIAS** [comment]
Hello,

Thanks, again, a lot for all.

I have tested the new version 15.01.2 and using the new features to obtain fileids individually as sohwn next in detail

C:\Users\ANGEL>onedrive-cli -V
python-onedrive 15.02.2

C:\Users\ANGEL>onedrive-cli -c "B:\OD.lcrc" -k id info "ALQS2D/xCONTROL/TAZAS/PRUPY.txt"
file.6ea482f9ed79f808.6EA482F9ED79F808!74586

And thanks again for your indications about programs to generate an executable: py2exe, Pyinstaller y cx_Freeze. That is my next step. 

I am sincerely grateful to you

**Comment by mk-fg** [comment]
You're welcome, thanks for parsing all those ridiculous walls of rambling text I tend to throw at people.
Someone was bound to stumble upon these limitations or missing features sooner or later, and fixes were fairly trivial anyway, certainly shorter than I might make them sound in the description, so it's no problem.

With regards to the question, I guess you mean the output that you see in the "cmd" window (assuming it is, from a screenshot and windows environment), obviously downloaded files (which might also be considered to be "results") will be put in the current dir or wherever is specified.

onedrive-cli uses [standard streams](https://en.wikipedia.org/wiki/Standard_streams) (stdout, stderr) for all output, and application that runs it can redirect/substitute them for onedrive-cli to wherever it wants ([pipes](https://en.wikipedia.org/wiki/Anonymous_pipe), usually) and then read output from there.
Which is a complicated way of saying "that output goes wherever application wants it to".

For instance, in python you can do (using standard [subprocess](https://docs.python.org/2/library/subprocess.html) module):

    >>> import subprocess
    >>> output = subprocess.check_output(
    ...   ['onedrive-cli', '-c', 'B:\OD.lcrc',
    ...    '-k', 'id', 'info', 'ALQS2D/xCONTROL/TAZAS/PRUPY.txt' ])
    >>> output
    'file.6ea482f9ed79f808.6EA482F9ED79F808!74586\n'
    >>> file_id = output.strip()
    >>> file_id
    'file.6ea482f9ed79f808.6EA482F9ED79F808!74586'

(though from python, of course you can do it easier by just importing "onedrive" module)

There, output of a subprocess was captured as a python string, to use later in the script somewhere.
In most unix shells, you'd do same thing via `file_id=$(onedrive-cli ...)`, I think windows batch scripting language allows something like that too (though I wouldn't recommend writing any but the most trivial applications in it).
