### ISSUE TITLE
Stuck at `URL after last redirect`

### ISSUE THREAD

**Issue by qxlab** [mk-fg/python-onedrive#53]
I tried to setup running `onedrive-cli auth` but it gets stuck when I enter the `URL after last redirect`

**Comment by mk-fg** [comment]
If it gets stuck indefinitely (i.e. there's no network timeout error after a minute or few), I suspect that it's just entering the URL that doesn't work, which I think happened before on some systems.

Try using "auth" command with that URL as an argument (as probably suggested as an alternative in the message it gives you).
That way, it shouldn't ask you anything, just reliably go straight to requesting the access.

**Comment by qxlab** [comment]
Ok, I'll run everything again and then see what happens. I'll report it back here. Thanks.

**Comment by brookhong** [comment]
I had this issue on my MacBook pro and a desktop running ubuntu 12.10.

**Comment by mk-fg** [comment]
@brookhong 
In the past (as in few months ago), or just recently?

I'm asking because I did make some changes there, I think a few months ago, loading readline to (hopefully) make python's raw_input() catch "press Enter" event better, but no idea if it helped or not, as I never reproduced the issue.

Dunno about OSX, but it's especially surprising for Ubuntu, which should have like the most common terminals and setup, really weird.

And I also wonder what do you mean by "had"?
Did the issue go away by itself, or did you work around it somehow (maybe in a way proposed in the comment above)?

In any case, thanks for that remark about ubuntu, I think I had ubuntu 12 vm around, might try how it works there, try to reproduce the thing (which is much harder to do with OSX, of course, which I think the previous such report was about).

**Comment by mk-fg** [comment]
I suspect that "being stuck" thing was due to encodings hack mentioned (and removed) in #54, so with current git master (or pypi version), this URL input might work better.

**Comment by brookhong** [comment]
I worked around by `onedrive-cli auth <URL after last redirect>`, that's why I use `had`, actually I came across this issue just two days ago.

Then encoding hack is made after `auth`, that can not be the reason.

**Comment by mk-fg** [comment]
> Then encoding hack is made after auth, that can not be the reason.

No, you misunderstood, I mean the hack that was previously in place there:

    import codecs
    sys.stdin = codecs.getreader(optz.encoding)(sys.stdin)
    sys.stdout = codecs.getwriter(optz.encoding)(sys.stdout)

This one was in place since "Sat Mar 9 18:01:26 2013 +0600", so definitely there when you both used `auth` command.

**Comment by mk-fg** [comment]
I'm not sure it affects `raw_input()` though, as that might be implemented in C and not be using `sys.stdin` at all.

**Comment by qxlab** [comment]
It didn't work. 

(Sorry but I've installed onedrive-d and it's working). 

Thanks a lot.

**Comment by mk-fg** [comment]
Tried "auth" in the current version on ubuntu 12.04.4 LTS VM, default terminal, zsh and bash - worked fine, though not sure if 12.10 is different.
