### ISSUE TITLE
Upgrade to Python3

### ISSUE THREAD

**Issue by m2kar** [mk-fg/python-onedrive#65]
This project's python version is 2.7, which will be retired by April 2020.

Could this project upgrade to the python3, improve security of the repo and ease of maintenance.

**Comment by mk-fg** [comment]
But this project is already retired too, same as python it was written on! :)

I mean, its description blurb states:
"Obsolete python/cli module for MS SkyDrive/OneDrive's old API, do not use for new projects"

And first line of the README is:
"**Deprecation Warning:** this module is completely obsoleted by official onedrive-sdk-python, for all new projects please use that instead."

It's for an old experimental API of OneDrive, which is also obsolete, and I guess they only haven't retired it yet because some enterprise projects might still be using it due to sheer inertia.

Use official onedrive-sdk-python module for their modern API instead of this one.
